### ISSUE TITLE
How to ignore case from graphql query?

### ISSUE THREAD

**Issue by wangsongiam** [KyleAMathews/blog#14]
Hi! Kyle, I followed your way of the [tag page](https://github.com/KyleAMathews/blog/blob/master/src/templates/tag-page.js),  but I found those tags are case sensitive. If I have a tag "Vim" and another tag "vim", they will be separated like this 
<img width="170" alt="screen shot 2017-08-13 at 3 06 36 am" src="https://user-images.githubusercontent.com/19645990/29246914-933d5718-7fd4-11e7-8192-96b4a0bea69c.png">

Any idea to fix this problem?

**Comment by KyleAMathews** [comment]
In Gatsby, we don't have a way yet to set case sensitivity in queries. Could you open an issue in the Gatsby repo on this?

**Comment by wangsongiam** [comment]
Of course
