### ISSUE TITLE
webpage can not find the relative URLs as all resources point to root(/)

### ISSUE THREAD

**Issue by naqushab** [KyleAMathews/blog#15]
I see that the webpage can not find the relative URLs; as all resources point to root(/).
So, if a user has blog at [http://abc.xyz/blog/](http://abc.xyz/blog/) ; it searches for resources @ [http://abc.xyz/](http://abc.xyz/)

**Comment by KyleAMathews** [comment]
Not here on the gatsby repo :-)

Also, try reading https://www.gatsbyjs.org/docs/deploy-gatsby/

**Comment by naqushab** [comment]
Oh! Sorry.

**Comment by naqushab** [comment]
Thanks a lot Kyle. It helped. :)
On 8/25/2017 1:14:56 AM, Kyle Mathews <notifications@github.com> wrote:
Not here on the gatsby repo :-)
Also, try reading https://www.gatsbyjs.org/docs/deploy-gatsby/ [https://www.gatsbyjs.org/docs/deploy-gatsby/]
