### ISSUE TITLE
Your website is not accessible anymore.

### ISSUE THREAD

**Issue by shakilmith** [KyleAMathews/blog#87]
Hi, your website called http://bricolage.io/ is not accessible or can be routed through major browsers.

![Screenshot 2024-10-18 094312](https://github.com/user-attachments/assets/616fdc6d-d28c-4d39-9e1c-fe66a1b7a0e4)

**Comment by KyleAMathews** [comment]
Fixed thanks https://github.com/KyleAMathews/blog/commit/150ce9cc0364e22211d6844b28957167b02be228
